### ISSUE TITLE
Entries in "Family Tree Overview" menu are lost after update to beta2 version

### ISSUE THREAD

**Issue by Jefferson49** [JustCarmen/webtrees-fancy-treeview#100]
After updating the module files to the 2.0.0-beta2 release, the entries in the "Family Tree Overview" menu were lost. For future module updates, the entries should be still available after the update.

**Comment by JustCarmen** [comment]
Yes, that is true. I did mentioned it in the forum that due to a change in the way menu items are stored in the database, all settings from the beta 1 version have been lost. But you may not have seen that [post](https://www.webtrees.net/index.php/en/forum/4-customising/37471-fancy-treeview-module-for-webtrees-2?start=20#95921).

This was a one-time change, so menu items should be retained in the next version.

**Comment by Jefferson49** [comment]
Thank you for checking the issue.

After upgrading from beta2 to the beta3 version it works fine!
