### ISSUE TITLE
Beta 3 - Heading is missing

### ISSUE THREAD

**Issue by heiler** [JustCarmen/webtrees-fancy-treeview#101]
In both the ancestor and the descendant view, the "Generation 4" heading is missing.

https://www.heiler-ahnen.de/webtrees/tree/heiler/jc-fancy-treeview/I0077/johannes-christoph-josef-heiler/descendants/2#4

https://www.heiler-ahnen.de/webtrees/tree/heiler/jc-fancy-treeview/I0160/theodor-heiler/ancestors/2#4

**Comment by JustCarmen** [comment]
I think you are using a custom css that was used to solve some scrolling problems by using the :target tag. I think you should remove the custom css because it is not necessary anymore.

You are also using the JustLight theme. There we have the problem that scrolling to target does not work properly because of the sticky header. I recently fixed that within the theme, but that part has not been released yet. I need to fix a few issues and then I will set up a new release of the JustLight theme. After that, everything should work correctly. But it should already work correctly in the standard Webtrees themes.

**Comment by JustCarmen** [comment]
> I added the css, because I needed it for a "Simple Menu" page. 
Oh I remember now. I think I have told you myself how to solve that issue ;)

>  After Updating the theme it should become redundant.
Correct. But for the time being (maybe one or two days) you could solve the issue by adding this to your css/js module:
`@media (min-width: 992px) {
  html {
    scroll-padding-top: 160px;
  }
}`

and remove the old 'target' css.

> Generation 7 is correctly displayed . What is the difference?
The difference is that when using the read more link we don't know for sure if the next generation is at the top of the page. If someone chose to display 5 generations on the page and 3 on the tab, you have to scroll down a lot to reach the 4th generation after clicking the read more link. So that's where the target link comes in. But on second thought this is not necessary when the generation to reach is at the top of the page.
When using the page buttons to go to the next page the next generation is always at the top of the page. No need to scroll down the page.

**Comment by heiler** [comment]
Thank you Carmen, it works.

**Comment by JustCarmen** [comment]
I've just released [version 2.2.4](https://github.com/JustCarmen/webtrees-theme-justlight/releases/tag/2.2.4) of the JustLight theme with solves your issue. You no longer need custom css.
