### ISSUE TITLE
the list of tabs disappears on the 2nd page

### ISSUE THREAD

**Issue by Fa10175** [JustCarmen/webtrees-fancy-treeview#108]
see 

https://www.webtrees.net/index.php/fr/forum/4-customising/37471-fancy-treeview-module-for-webtrees-2?start=40#96291

**Comment by hartenthaler** [comment]
For me, this is a feature, not a bug. Using more space on the screen for the report is more important for me than showing the tabs. But ok, this is my opinion.

**Comment by JustCarmen** [comment]
You are right Herman. That's why I didn't mark it as a bug.

When leaving the individual page by clicking the read more link there is no smart option to go back to the individual page., other then using the browser back button or clicking on the name of the first person in the first generation on the first page, who is the root person.

I agree this is inconvenient. To make it a little bit easier I've put a link on the name in the title which leads (back) to the individual page. I hope this helps.

**Comment by Fa10175** [comment]
this helps a little, but its hard to explain to the member of a tree how do a go-back and change tab to this person 

I hope in the future you can find a solution to keep the spirit of the tabs

**Comment by JustCarmen** [comment]
If I understand you correctly you don't want to navigate away from the individual page. But that is not possible I am afraid.  I cannot divide the tab into multiple pages and a long list of all generations within the tab is not desirable either.  So in order to show the rest of the generations we need to link to the Fancy Treeview page. It is a separate environment with multiple pages to show all generations of the individual. That page doesn't have tabs.

Perhaps there are other places to put the link to the individual page, but I chose to put the name in the title so as not to overcrowd the page.

**Comment by Fa10175** [comment]
"_Perhaps there are other places to put the link to the individual page, but I chose to put the name in the title so as not to overcrowd the page._"

this point is very good.

this module which existed in 1.7 of webtrees had disappeared since what I regretted.
you could have a beam on some people of the tree.

and you found how to do even better in version 2.1, the function available in addition for each person.

I have hope in the future

**Comment by Fa10175** [comment]
for info, seeing the issue #116, I modified in the database the table wt_module_setting the tab-limit field from _jc-fancy-treeview_ to 20
and by testing it answers my request
