### ISSUE TITLE
feature request: make chronological order of the generations configurable

### ISSUE THREAD

**Issue by Bogiegit** [JustCarmen/webtrees-fancy-treeview#99]
It should be said in advance the reading direction of the report is always top down.
In beta 2 descendants are listed from older generations to younger and ancestors are listed from younger generations to older.

If possible, I would suggest to keep the direction in all cases from 'previous to present' or from 'present to previous' depending on the user setting.

**Comment by JustCarmen** [comment]
Personally, I think it will complicate things. I think most readers expect the base person to be listed first and not last. So I would probably add a third (default) option to leave the base person always on top.

I don't know if it is very difficult to change the point of view, so that will help determine whether I end up implementing this request.

**Comment by JustCarmen** [comment]
I decided not to implement this. As far as I have been able to find out, it is not common to reverse the reading direction. Therefore, I remain of the opinion that the list should always start with the basic person (the proband) and I think this is also what the reader expects.

I am therefore going to close this topic.
